ConnectionStrings: 
    MicroservicesClientConnectionString: Data Source=.;Initial Catalog=Library;Persist Security Info=True;User ID=sa;Password=Password1234  
JwtSettings: 
    Key: nskljgfdgokwernglsndgjknsñdjgnskjdfgnlkjsdnfskdjgsdjfkg
    Issuer: https://localhost:44323/
    Audience: Microservices.ConfigServer.Client
    MinutesToExpiration: 10
  
