ConnectionStrings: 
    MicroservicesClientConnectionString: Data Source=.;Initial Catalog=LibraryRelease;Persist Security Info=True;User ID=andresito;Password=Password123  
JwtSettings: 
    Audience: Microservices.ConfigServer.ClientRelease  
  
